version: '3'

volumes:
    data: {}

services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        image: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        restart: "always"
        networks:
            - gaepo
    # wordpress:
    #     build:
    #         context: ./requirements/wordpress
    #         dockerfile: ./Dockerfile
    #     container_name: wordpress
    #     volumes:
    #         - data:/var/www/html
    #     restart: always
    #     networks:
    #         - gaepo

networks:
    gaepo:
        driver: bridge