version: '3'

services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        image: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        restart: "always"
        volumes:
            - wordpress:/var/www/html
        networks:
            - gaepo
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: ./Dockerfile
        container_name: wordpress
        image: wordpress
        volumes:
            - data:/var/www/html
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - gaepo

networks:
    gaepo:
        driver: bridge

volumes:
    wordpress: {}
    