version: '3'

volumes:
    vol_wordpress:
        driver: local
        driver_opts:
            type: volume
            device: /Users/kiyoon/goinfre/inception/srcs/requirements/tools
            o: bind

services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        image: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        restart: "always"
        volumes:
            - vol_wordpress:/var/www/html
        networks:
            - gaepo
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: ./Dockerfile
        container_name: wordpress
        image: wordpress
        restart: always
        volumes:
            - vol_wordpress:/var/www/html
        networks:
            - gaepo

networks:
    gaepo:
        driver: bridge
