version: '3'

volumes:
    vol_wordpress: 
        driver: local
        driver_opts:
            type: volume
            device: ./requirements/tools/wordpress
            o: bind
    vol_mariadb:
        driver: local
        driver_opts:
            type: volume
            device: ./requirements/tools/mariadb
            o: bind

services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        image: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        restart: "always"
        volumes:
            - vol_wordpress:/var/www/html/
        networks:
            - gaepo
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: ./Dockerfile
        container_name: wordpress
        image: wordpress
        # depends_on:
        #     - mariadb
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT: ${MYSQL_ROOT}
        volumes:
            - vol_wordpress:/var/www/html/
        expose:
            - "9000"
        networks:
            - gaepo
    # mariadb:
    #     build:
    #         context: ./requirements/mariadb
    #         dockerfile: ./Dockerfile
    #     container_name: mariadb
    #     image: mariadb
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #     volumes:
    #         - vol_mariadb:/var/lib/mysql
    #     networks:
    #         - gaepo

networks:
    gaepo:
        driver: bridge
